import { Readex_Pro } from "next/font/google";
import "./globals.css";


const readexPro = Readex_Pro({
  variable: "--font-readex-pro",
  subsets: ["latin"], 
});

export const metadata = {
  title: "Zetime",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body
        className={`${readexPro.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
